import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov', 'json-summary'],
      reportsDirectory: 'coverage',
      clean: true,
      thresholds: {
        branches: 80,
        functions: 75,
        lines: 90,
        statements: 90,
      },
      exclude: [
        '**/*.d.ts',
        '**/dist/**',
        '**/build/**',
        '**/tests/**',
        '**/node_modules/**',
        '**/*.config.*',
        '**/*.conf.*',
        '**/index.ts',
        'scripts/**',
        'apps/designer/**',
        'apps/gateway/**',
        'cucumber.cjs',
        'vitest.workspace.ts',
        'examples/**',
        'packages/domain/src/execution-plan/execution-plan.ts',
        'packages/domain/src/pipeline/pipeline-definition.ts',
        'packages/domain/src/pipeline/pipeline-io.ts',
        'packages/domain/src/pipeline/pipeline-node.ts',
        'packages/domain/src/pipeline/pipeline-edge.ts',
        'packages/domain/src/capability/capability-definition.ts',
        'packages/domain/src/ports/**',
        'packages/domain/src/provenance/provenance-record.ts',
        'packages/domain/src/registry/registry-types.ts',
        'packages/domain/src/discovery/discovery-types.ts',
        'packages/codegen/src/cli.ts',
      ],
    },
  },
});
