import type { SemanticTypeRegistry } from '@eve-fabric/core';
import type { ResolvedWeave } from './generator.js';
import { tsTypeOf } from './type-mapper.js';

/** `forge prices` as an identifier: forgePrices. A name that starts with a digit is prefixed. */
export function identifierOf(name: string): string {
  const words = name.split(/[^A-Za-z0-9]+/).filter((w) => w.length > 0);
  const camel = words
    .map((w, i) => (i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1)))
    .join('');
  return /^[A-Za-z_$]/.test(camel) ? camel : `ask${camel}`;
}

function pascal(identifier: string): string {
  return identifier.charAt(0).toUpperCase() + identifier.slice(1);
}

/** `type Name = { port: type; … }`, each port with its semantic type as a comment. */
function emitShape(
  name: string,
  ports: Readonly<Record<string, string>>,
  types: SemanticTypeRegistry,
): string {
  const lines = [`export type ${name} = {`];
  for (const [port, type] of Object.entries(ports)) {
    lines.push(`  /** ${type} */`, `  ${port}: ${tsTypeOf(type, types)};`);
  }
  lines.push('};');
  return lines.join('\n');
}

/**
 * The generated module: the weave as exported, the shape of what it takes and
 * gives, and one function. The function builds a fabric over the core pack
 * and the packs the caller passes, adds the weave to it (digest, requirements
 * and scopes checked as `weave add` checks them), and runs the question with
 * the inputs given by port. The fabric is built once per options object.
 */
export function emitIndexTs(weave: ResolvedWeave, types: SemanticTypeRegistry): string {
  const { file } = weave;
  const fn = identifierOf(file.name);
  const Input = `${pascal(fn)}Input`;
  const Output = `${pascal(fn)}Output`;
  const usesEsi = weave.sources.has('ESI');
  const usesSde = weave.sources.has('SDE');
  const scoped = file.scopes.length > 0;

  const header = [
    '/**',
    ` * ${file.name}: ${file.description}`,
    ' *',
    ` * Generated by @eve-fabric/codegen from the weave ${file.id}@${file.version}. The`,
    ' * weave is embedded below and added to a fabric when first asked; this module',
    ' * carries no capability code. It requires:',
    ...Object.entries(file.requires).map(([id, range]) => ` *   ${id} ${range}`),
  ];
  if (scoped)
    header.push(
      ' *',
      ` * Its steps need the scopes ${file.scopes.join(', ')}: pass the character as \`as\`.`,
    );
  header.push(' */', '');

  const imports = [
    `import { createFabric, type Fabric, type FabricOptions${scoped ? ', type FabricIdentity' : ''} } from '@eve-fabric/fabric';`,
    `import { corePack } from '@eve-fabric/pack-core';`,
  ];
  if (usesEsi) imports.push(`import { createEsi } from '@lgriffin/esi.ts/client';`);
  if (usesSde) imports.push(`import { lazySdeDirectory } from '@eve-fabric/source-sde';`);

  const defaults: string[] = [];
  if (usesEsi) {
    defaults.push(
      '  // Who is calling ESI, as CCP asks every application to say.',
      '  if (options.esi === undefined) {',
      "    defaults.esi = createEsi({ userAgent: process.env['ESI_USER_AGENT'] ?? 'eve-fabric/0.1 (+https://github.com/lgriffin/eve-fabric)' });",
      '  }',
    );
  }
  if (usesSde) {
    defaults.push(
      '  // Names resolve through the SDE export at SDE_DATA_PATH, unless a source is given.',
      "  if (options.sde === undefined && process.env['SDE_DATA_PATH'] !== undefined) {",
      "    defaults.sde = lazySdeDirectory(process.env['SDE_DATA_PATH']);",
      '  }',
    );
  }

  const asParam = scoped ? ',\n  as?: FabricIdentity' : '';
  const asArg = scoped ? ', as' : '';

  return [
    ...header,
    ...imports,
    '',
    '/** The weave this module runs, as it was exported; its digest is checked when it is added. */',
    `export const WEAVE: string = ${JSON.stringify(weave.yaml)};`,
    '',
    emitShape(Input, file.provides.in, types),
    '',
    emitShape(Output, file.provides.out, types),
    '',
    "type Ready = { readonly fabric: Fabric; readonly capability: Awaited<ReturnType<Fabric['add']>> };",
    '',
    'async function build(options: FabricOptions): Promise<Ready> {',
    "  const defaults: { esi?: FabricOptions['esi']; sde?: FabricOptions['sde'] } = {};",
    ...defaults,
    '  const fabric = createFabric({ ...defaults, ...options, packs: [corePack, ...(options.packs ?? [])] });',
    '  const capability = await fabric.add(WEAVE);',
    '  return { fabric, capability };',
    '}',
    '',
    '// One fabric per options object, so the SDE loads once and the caches last across calls.',
    'const DEFAULT_OPTIONS: FabricOptions = {};',
    'const ready = new WeakMap<FabricOptions, Promise<Ready>>();',
    '',
    'function readyFor(options: FabricOptions): Promise<Ready> {',
    '  let building = ready.get(options);',
    '  if (building === undefined) {',
    '    building = build(options);',
    '    ready.set(options, building);',
    '  }',
    '  return building;',
    '}',
    '',
    `export async function ${fn}(`,
    `  input: ${Input},`,
    `  options: FabricOptions = DEFAULT_OPTIONS${asParam},`,
    `): Promise<${Output}> {`,
    '  const { fabric, capability } = await readyFor(options);',
    `  return (await fabric.runOne(capability, input${asArg})) as ${Output};`,
    '}',
    '',
    `export default ${fn};`,
    '',
  ].join('\n');
}
