import type { ExecutionPlan, PipelineDefinition, CapabilityDefinition } from '@eve-fabric/domain';
import { semanticTypeToTs } from './type-mapper.js';

function toCamelCase(str: string): string {
  return str.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

function toPascalCase(str: string): string {
  const camel = toCamelCase(str);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((line) => (line.trim() ? pad + line : line))
    .join('\n');
}

function serializeCapabilityToCode(def: CapabilityDefinition): string {
  const inputs: Record<string, Record<string, unknown>> = {};
  for (const [name, port] of def.inputs) {
    const entry: Record<string, unknown> = { type: port.semanticType };
    if (port.description) entry.description = port.description;
    entry.required = port.required;
    inputs[name] = entry;
  }

  const outputs: Record<string, Record<string, unknown>> = {};
  for (const [name, port] of def.outputs) {
    const entry: Record<string, unknown> = { type: port.semanticType };
    if (port.description) entry.description = port.description;
    outputs[name] = entry;
  }

  const config: Record<string, unknown> = {
    id: def.id,
    version: def.version,
    name: def.name,
    description: def.description,
    inputs,
    outputs,
    source: def.source,
  };

  if (def.dependencies.length > 0) {
    config.dependencies = def.dependencies.map((d) => d.id as string);
  }

  config.auth = { required: def.auth.required, scopes: def.auth.scopes };
  config.cache = {
    cacheable: def.cache.cacheable,
    defaultTtlSeconds: def.cache.defaultTtlSeconds,
    stalePermitted: def.cache.stalePermitted,
    identityInKey: def.cache.identityInKey,
  };
  config.cost = {
    estimatedLatencyMs: def.cost.estimatedLatencyMs,
    esiCallCount: def.cost.esiCallCount,
  };

  return `defineCapability(${JSON.stringify(config, null, 2)})`;
}

function serializePlanToCode(plan: ExecutionPlan): string {
  const datePlaceholder = '__CODEGEN_DATE__';

  const serializable = {
    id: plan.id,
    pipelineRef: plan.pipelineRef,
    steps: plan.steps.map((s) => ({
      id: s.id,
      capability: {
        id: s.capability.id,
        ...(s.capability.version !== undefined ? { version: s.capability.version } : {}),
      },
      inputs: s.inputs.map((i) => ({ ...i })),
      dependsOn: [...s.dependsOn],
      ...(s.cacheKey !== undefined ? { cacheKey: s.cacheKey } : {}),
      canParallelize: s.canParallelize,
    })),
    parallelGroups: plan.parallelGroups.map((g) => ({
      steps: [...g.steps],
      canParallelize: g.canParallelize,
    })),
    sourceRequirements: plan.sourceRequirements.map((r) => ({
      source: r.source,
      capabilities: r.capabilities.map((c) => ({
        id: c.id,
        ...(c.version !== undefined ? { version: c.version } : {}),
      })),
    })),
    authRequirements: {
      required: plan.authRequirements.required,
      scopes: [...plan.authRequirements.scopes],
    },
    cacheStrategy: plan.cacheStrategy.map((c) => ({ ...c })),
    costEstimate: { ...plan.costEstimate },
    createdAt: datePlaceholder,
  };

  let json = JSON.stringify(serializable, null, 2);
  json = json.replace(
    `"${datePlaceholder}"`,
    `new Date(${JSON.stringify(plan.createdAt.toISOString())})`,
  );

  return json;
}

function emitInputInterface(name: string, pipeline: PipelineDefinition): string {
  const lines = [`export interface ${name} {`];
  for (const input of pipeline.inputs) {
    const tsType = semanticTypeToTs(input.semanticType);
    const optional = input.required ? '' : '?';
    lines.push(`  /** ${input.semanticType as string} */`);
    lines.push(`  ${input.name}${optional}: ${tsType};`);
  }
  lines.push('}');
  return lines.join('\n');
}

export function emitIndexTs(
  pipeline: PipelineDefinition,
  plan: ExecutionPlan,
  capabilities: readonly CapabilityDefinition[],
  _graphqlSdl?: string,
): string {
  const funcName = toCamelCase(pipeline.id);
  const pascalName = toPascalCase(pipeline.id);
  const inputTypeName = `${pascalName}Input`;

  const sources = new Set(plan.sourceRequirements.map((r) => r.source));

  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * ${pipeline.name}`);
  if (pipeline.description) {
    lines.push(` *`);
    lines.push(` * ${pipeline.description}`);
  }
  lines.push(` *`);
  lines.push(` * Generated by eve-fabric codegen from pipeline.yaml`);
  lines.push(` * To modify: load pipeline.yaml into the eve-fabric designer`);
  lines.push(` */`);
  lines.push('');

  // Imports
  lines.push(`import { Executor, type ExecutionResult } from '@eve-fabric/executor';`);
  lines.push(`import { CapabilityCatalog, type ExecutionPlan } from '@eve-fabric/domain';`);
  lines.push(`import { defineCapability } from '@eve-fabric/capability-sdk';`);

  if (sources.has('ESI')) {
    lines.push(`import { EsiAdapter } from '@eve-fabric/esi-adapter';`);
  }
  if (sources.has('SDE')) {
    lines.push(`import { SdeAdapter } from '@eve-fabric/sde-adapter';`);
  }
  if (sources.has('DERIVED')) {
    lines.push(`import { DerivedAdapter } from '@eve-fabric/executor';`);
  }

  lines.push('');

  // Capabilities
  lines.push('// Capabilities used by this pipeline');
  lines.push('const capabilities = [');
  for (let i = 0; i < capabilities.length; i++) {
    const capCode = serializeCapabilityToCode(capabilities[i]!);
    lines.push(indent(capCode, 2) + ',');
  }
  lines.push('];');
  lines.push('');

  // Plan
  lines.push('// Compiled execution plan');
  lines.push(`const plan = ${serializePlanToCode(plan)} as unknown as ExecutionPlan;`);
  lines.push('');

  // Catalog factory
  lines.push('function createCatalog(): CapabilityCatalog {');
  lines.push('  const catalog = new CapabilityCatalog();');
  lines.push('  for (const cap of capabilities) {');
  lines.push('    catalog.register(cap);');
  lines.push('  }');
  lines.push('  return catalog;');
  lines.push('}');
  lines.push('');

  // Input interface
  lines.push(emitInputInterface(inputTypeName, pipeline));
  lines.push('');

  // Adapter instantiation
  const adapterExprs: string[] = [];
  if (sources.has('ESI')) adapterExprs.push('new EsiAdapter()');
  if (sources.has('SDE')) adapterExprs.push('new SdeAdapter()');
  if (sources.has('DERIVED')) adapterExprs.push('new DerivedAdapter()');
  if (adapterExprs.length === 0) adapterExprs.push('/* no adapters */');

  // Main function
  lines.push(
    `export async function ${funcName}(input: ${inputTypeName}): Promise<ExecutionResult> {`,
  );
  lines.push('  const executor = new Executor({');
  lines.push(`    adapters: [${adapterExprs.join(', ')}],`);
  lines.push('    catalog: createCatalog(),');
  lines.push('  });');
  lines.push('  const inputMap = new Map<string, unknown>(Object.entries(input));');
  lines.push('  return executor.execute(plan, inputMap);');
  lines.push('}');
  lines.push('');

  lines.push(`export default ${funcName};`);
  lines.push('');

  return lines.join('\n');
}
