import type { ExecutionPlan, PipelineDefinition, CapabilityDefinition } from '@eve-fabric/domain';
import { semanticTypeToTs } from './type-mapper.js';

function toCamelCase(str: string): string {
  return str.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

function toPascalCase(str: string): string {
  const camel = toCamelCase(str);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function serializePlanToCode(plan: ExecutionPlan): string {
  const datePlaceholder = '__CODEGEN_DATE__';

  const serializable = {
    id: plan.id,
    pipelineRef: plan.pipelineRef,
    steps: plan.steps.map((s) => ({
      id: s.id,
      capability: {
        id: s.capability.id,
        ...(s.capability.version !== undefined ? { version: s.capability.version } : {}),
      },
      inputs: s.inputs.map((i) => ({ ...i })),
      dependsOn: [...s.dependsOn],
      ...(s.cacheKey !== undefined ? { cacheKey: s.cacheKey } : {}),
      canParallelize: s.canParallelize,
    })),
    parallelGroups: plan.parallelGroups.map((g) => ({
      steps: [...g.steps],
      canParallelize: g.canParallelize,
    })),
    sourceRequirements: plan.sourceRequirements.map((r) => ({
      source: r.source,
      capabilities: r.capabilities.map((c) => ({
        id: c.id,
        ...(c.version !== undefined ? { version: c.version } : {}),
      })),
    })),
    authRequirements: {
      required: plan.authRequirements.required,
      scopes: [...plan.authRequirements.scopes],
    },
    cacheStrategy: plan.cacheStrategy.map((c) => ({ ...c })),
    costEstimate: { ...plan.costEstimate },
    createdAt: datePlaceholder,
  };

  let json = JSON.stringify(serializable, null, 2);
  json = json.replace(
    `"${datePlaceholder}"`,
    `new Date(${JSON.stringify(plan.createdAt.toISOString())})`,
  );

  return json;
}

function emitInputInterface(name: string, pipeline: PipelineDefinition): string {
  const lines = [`export interface ${name} {`];
  for (const input of pipeline.inputs) {
    const tsType = semanticTypeToTs(input.semanticType);
    const optional = input.required ? '' : '?';
    lines.push(`  /** ${input.semanticType as string} */`);
    lines.push(`  ${input.name}${optional}: ${tsType};`);
  }
  lines.push('}');
  return lines.join('\n');
}

/**
 * The generated module runs its compiled plan on a fabric with the core pack.
 * It carries no capability code: the pack supplies each pinned capability.
 */
export function emitIndexTs(
  pipeline: PipelineDefinition,
  plan: ExecutionPlan,
  capabilities: readonly CapabilityDefinition[],
  _graphqlSdl?: string,
): string {
  const funcName = toCamelCase(pipeline.id);
  const pascalName = toPascalCase(pipeline.id);
  const inputTypeName = `${pascalName}Input`;

  const sources = new Set(plan.sourceRequirements.map((r) => r.source));
  const usesEsi = sources.has('ESI');
  const usesSde = sources.has('SDE');

  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * ${pipeline.name}`);
  if (pipeline.description) {
    lines.push(` *`);
    lines.push(` * ${pipeline.description}`);
  }
  lines.push(` *`);
  lines.push(` * Capabilities (from @eve-fabric/pack-core):`);
  for (const cap of capabilities) {
    lines.push(` *   ${cap.id as string}@${cap.version as string}`);
  }
  lines.push(` *`);
  lines.push(` * Generated by eve-fabric codegen from pipeline.yaml`);
  lines.push(` * To modify: load pipeline.yaml into the eve-fabric designer`);
  lines.push(` */`);
  lines.push('');

  // Imports
  lines.push(`import { createFabric, type FabricOptions } from '@eve-fabric/fabric';`);
  lines.push(`import { corePack } from '@eve-fabric/pack-core';`);
  lines.push(`import type { ExecutionResult } from '@eve-fabric/executor';`);
  lines.push(`import type { ExecutionPlan } from '@eve-fabric/domain';`);
  if (usesEsi) lines.push(`import { createEsi } from '@lgriffin/esi.ts/client';`);
  if (usesSde) lines.push(`import { loadSdeDirectory } from '@eve-fabric/source-sde';`);
  lines.push('');

  // Plan
  lines.push('// Compiled execution plan');
  lines.push(`const plan = ${serializePlanToCode(plan)} as unknown as ExecutionPlan;`);
  lines.push('');

  // Input interface
  lines.push(emitInputInterface(inputTypeName, pipeline));
  lines.push('');

  // Main function
  lines.push(
    `export async function ${funcName}(`,
    `  input: ${inputTypeName},`,
    `  options: FabricOptions = {},`,
    `): Promise<ExecutionResult> {`,
    '  const fabric = createFabric({',
  );
  if (usesEsi) {
    lines.push(
      '    // Who is calling ESI, as CCP asks every application to say.',
      '    esi: createEsi({',
      "      userAgent: process.env['ESI_USER_AGENT'] ?? 'eve-fabric/0.1 (+https://github.com/lgriffin/eve-fabric)',",
      '    }),',
    );
  }
  if (usesSde) {
    lines.push(
      "    ...(process.env['SDE_DATA_PATH'] ? { sde: loadSdeDirectory(process.env['SDE_DATA_PATH']) } : {}),",
    );
  }
  lines.push(
    '    ...options,',
    '    packs: [corePack, ...(options.packs ?? [])],',
    '  });',
    '  return fabric.execute(plan, new Map<string, unknown>(Object.entries(input)));',
    '}',
    '',
    `export default ${funcName};`,
    '',
  );

  return lines.join('\n');
}
