/**
 * docs/cli.md, from the CLI's own help: the usage text is the one `eve-fabric
 * --help` prints, so the page cannot drift from the commands. `--check` fails
 * when the committed page differs from a fresh render (CI runs it).
 *
 * Run: pnpm run docs:cli [--check]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { format } from 'prettier';
import { USAGE } from '../apps/cli/src/cli.js';

const OUT = join(import.meta.dirname, '..', 'docs', 'cli.md');

const draft = `<!-- Generated by scripts/docs-cli.ts from the CLI's help text. Edit that script, not this file. -->

# The \`eve-fabric\` command line

In a checkout, \`pnpm fabric\` runs it from source. Once the packages are on
npm, \`npx @eve-fabric/cli\` runs it with nothing from this repository. Every
command takes the same fabric options, and nothing holds state between runs
except the SQLite file \`--db\` names.

## Usage

\`\`\`text
${USAGE}
\`\`\`

## Exit codes

| Code | Meaning                                                                   |
| ---- | ------------------------------------------------------------------------- |
| 0    | The command did what was asked.                                           |
| 1    | It failed: one \`error:\` line on stderr names the error and what went wrong. |
| 2    | The command line was not one it takes; the help text follows the error.   |

A question whose move no installed pack provides fails with a hint to pass
\`--pack <module>\`. A live run that cannot reach ESI says so and suggests
\`--offline\`.

## Environment

| Variable        | Read by                       | Meaning                                                              |
| --------------- | ----------------------------- | -------------------------------------------------------------------- |
| \`SDE_DATA_PATH\` | every command but \`weave\`, \`codegen\` | An SDE export directory, so live runs resolve names such as "Jita". Without it, live runs take ids only, and say so. |
| \`FABRIC_DB\`     | every command                 | The default for \`--db\`: a SQLite file that keeps added weaves across runs. |

\`--offline\` needs neither: names and data come from the recorded Tranquility
fixture (\`@eve-fabric/fixture\`), and no network call is made.

## Examples

The saved questions under \`examples/questions\` run offline:

\`\`\`bash
pnpm fabric --offline ask examples/questions/route-distance.graphql
pnpm fabric --offline ask examples/questions/trade-profit.graphql --json
pnpm fabric --offline moves type=Tritanium orders region="The Forge" cheapest
pnpm fabric --offline schema | head -40
\`\`\`

Sharing a question as a weave, adding it to a fabric that keeps it, and
turning it into a package:

\`\`\`bash
pnpm fabric --offline weave export examples/questions/trade-profit.graphql \\
  --id me.trade.profit --version 1.0.0 --as "my trade profit" --out trade-profit.weave.yaml
pnpm fabric --offline --db fabric.sqlite weave add trade-profit.weave.yaml
pnpm fabric --offline --db fabric.sqlite weave list
pnpm fabric --offline codegen trade-profit.weave.yaml --out ./trade-profit
\`\`\`

The generated directory holds the weave, an \`index.ts\` that builds a fabric
and asks the question by its ports, and a \`package.json\` naming the published
packages it needs.
`;

async function main(): Promise<void> {
  // Formatted as `pnpm run format` would, so the committed page is stable.
  const page = await format(draft, { filepath: OUT });
  if (process.argv.includes('--check')) {
    const current = readFileSync(OUT, 'utf8');
    if (current !== page) {
      console.error('docs/cli.md is out of date: run pnpm run docs:cli');
      process.exit(1);
    }
    console.log('docs/cli.md is current');
    return;
  }
  writeFileSync(OUT, page);
  console.log(`wrote ${OUT}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
